name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: make install

      # Test the flask application
      - name: Test Email Generator
        run: make test

      # Format the code
      - name: Format the code
        run: make format

      # Lint the code
      - name: Lint the code
        run: make lint

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t ${{ secrets.DOCKER_USERNAME }}/email-generator-app:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/email-generator-app:latest

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      - name: Log in to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418314331.dkr.ecr.us-east-1.amazonaws.com

      # Build and Push Docker image to AWS ECR
      - name: Build and Push to AWS ECR
        run: |
          docker buildx build --platform linux/amd64 -t 905418314331.dkr.ecr.us-east-1.amazonaws.com/email-generator:distroless .
          docker buildx build --platform linux/amd64 \-t 905418314331.dkr.ecr.us-east-1.amazonaws.com/email-generator:distroless \--load .
          docker push 905418314331.dkr.ecr.us-east-1.amazonaws.com/email-generator:distroless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
